### PR TITLE
add Cloudflare Workers to README

### PR DESCRIPTION
**Pull request by elithrar**
Adds an example for how to use Postgres.js with Cloudflare Workers.

### CODE REVIEW

**Comment by porsager** [comment]
Awesome Matt ! Thanks 😍

**Comment by dev-cetus** [comment]
hi! Is HYPERDRIVE mandatory, or does a simple `connectionString` work?

**Comment by elithrar** [comment]
@dev-cetus you can pass in a simple connection string, but each request will have to initiate a new connection to your database. This is both slow & won't scale on the database side.

**Comment by dev-cetus** [comment]
oh but, hyperdrive works only with paid plans...

**Pull request merged**
