### PR TITLE
feat: use ; as a delimiter for _box

### LINKED ISSUE #576: _box (box[]) isn't formatted/parsed as an array correctly
https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT
image
I am guessing since box has a different delimiter character the formatter and parser are messing up.

### PR DESCRIPTION
**Pull request by Bas950**
Resolve #576

### CODE REVIEW

**Comment by Bas950** [comment]
@porsager Could you re-run the failed tests, seems to be a concurrency thing.
When running all tests after each other, instead of all at once it seems to work...
image

**Comment by Bas950** [comment]
@porsager Not sure why it failed in the pr, while on my fork, exact same code it succeeds. Maybe re-run that failed run.
image

**Comment by porsager** [comment]
Yeah, it seems there are some race conditions sometimes causing the tests to fail. Haven't had time to look into it, but yeah, rerunning :P

**Comment by porsager** [comment]
PR looks fine 👍 thank you!

**Pull request merged**
