### PR TITLE
Add sql.partial``

### PR DESCRIPTION
**Pull request by yckao**
related to issue #12 

Maybe there will be other better way.
Just create a PR and want to have a discussion.

Can't wait to have feature like this since partial is essential in my use case.

### CODE REVIEW

**Comment by Minigugus** [comment]
Can just ```sql``;``` and ```sql.partial``;``` be the same?

I mean I know that ```sql``;``` returns a promise and therefore executes the query, but it might return an object with a `.then` function that actually executes the query, like a fake promise (works with await). Therefore the partials would simply be```sql``;``` not awaited:
```js
await sql`SELECT id FROM products ${price ? sql`WHERE price >= ${price}` : sql``}`;
```
Moreover, queries would also become reusable :wink:

**Comment by yckao** [comment]
@Minigugus Thanks.

I would like to keep using sql.partial because sql`` is already have so many duty, and I don't want increase complexity.
So I implemented sql.partial in a simplest way.

If let ``` sql`` ``` equal to ``` sql.partial`` ``` it will also effect the execute order with `send` and others because of the timing we parse value. That will be more complicated.

So I will keep sql.partial in this PR to keep it simple.

**Comment by porsager** [comment]
Hi @yckao 

This is great, and I'm sorry for my silence on the subject.. I already have plans for better dynamic queries to be included in v2, I just haven't been able to finish something to show yet.

My idea is to have ``` sql`` ``` work both ways as @Minigugus mentions. Since queries are already deferred to the next tick, any ``` sql`` ``` instance inside another ``` sql`` ``` call will simply not run.

That way I actually think we decrease user facing complexity because we keep the surface api / concepts lower,  and at the same time, automatic syntax highlighting many editors have for ``` sql`` ``` will just work.

It's also better for reusing and composing queries. 

The only caveat is that if you want to reuse or dont want to have your partial query inline it needs to be a function, and not a simple variable assignment. I actually find that a good thing since functions are first class, and many times you might want to pass some parameters as well.

Maybe we could also have an option of doing ``` sql``.partial ``` to support direct variable assignment, just like I'd like to have eg. ``` sql``.query ``` to inspect the actual query sent.

Also related to this, the idea is that ```sql()``` for building queries from objects / arrays will include more features.

**Comment by yckao** [comment]
> Hi @yckao
> 
> This is great, and I'm sorry for my silence on the subject.. I already have plans for better dynamic queries to be included in v2, I just haven't been able to finish something to show yet.
> 
> My idea is to have `` sql`` `` work both ways as @Minigugus mentions. Since queries are already deferred to the next tick, any `` sql`` `` instance inside another `` sql`` `` call will simply not run.
> 
> That way I actually think we decrease user facing complexity because we keep the surface api / concepts lower, and at the same time, automatic syntax highlighting many editors have for `` sql`` `` will just work.
> 
> It's also better for reusing and composing queries.
> 
> The only caveat is that if you want to reuse or dont want to have your partial query inline it needs to be a function, and not a simple variable assignment. I actually find that a good thing since functions are first class, and many times you might want to pass some parameters as well.
> 
> Maybe we could also have an option of doing `` sql``.partial `` to support direct variable assignment, just like I'd like to have eg. `` sql``.query `` to inspect the actual query sent.
> 
> Also related to this, the idea is that `sql()` for building queries from objects / arrays will include more features.

@porsager 
That's sounds good. Thanks for the kindly reply.
Actually I'm also have an idea to make sql`` without promise to work like [knex.toString()](http://knexjs.org/#Interfaces-toString)
So I can achieve what @Minigugus mentions above. Also can store partial query into variables.
(knex do that too.)

Also wondering is there any plan to add some options let user defined their own helpers?

And other problems is the usage of skip. I add this is because we cannot pass undefined into ${} (maybe it can but not in type definition, I haven't find out that).
Maybe we can let user passing undefined into ${} to skip the block?

This project is really great. Maybe you can add some roadmap or tasks, and let's community do it together ?
That's will be awesome if we could pushing amazing feature forward.

**Comment by stalniy** [comment]
I agree with @yckao that `sql` function is over overloaded :) This will make V8 to not be able to optimize this function for faster execution what is a downside.

The idea @yckao presented in https://github.com/porsager/postgres/pull/101#issuecomment-668193835 is much better than relying on  some inernals of event loop

**Comment by tomm** [comment]
I :+1: the original PR. I'd love this feature, since it would allow me to replace Slonik (a similar nodejs postgres interface, which allows sql partials but unfortunately has less than half the performance of porsager/postgres)

**Pull request closed without merging**
