### PR TITLE
Don't reassign to errors

### LINKED ISSUE #924: TypeError: Cannot redefine property: query
```
PostgresError: server conn crashed?
at ErrorResponse (file:///app/node_modules/postgres/src/connection.js:790:26)
at handle (file:///app/node_modules/postgres/src/connection.js:476:6)
at Socket.data (file:///app/node_modules/postgres/src/connection.js:315:9)
at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)
at addChunk (node:internal/streams/readable:559:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
at Readable.push (node:internal/streams/readable:390:5)
at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
at cachedError (file:///app/node_modules/postgres/src/query.js:170:23)
at new Query (file:///app/node_modules/postgres/src/query.js:36:24)
at sql (file:///app/node_modules/postgres/src/index.js:112:11)

file:///app/node_modules/postgres/src/connection.js:388
    Object.defineProperties(err, {

TypeError: Cannot redefine property: query
    at Function.defineProperties (<anonymous>)
    at queryError (file:///app/node_modules/postgres/src/connection.js:388:12)
    at error (file:///app/node_modules/postgres/src/connection.js:378:7)
    at Socket.closed (file:///app/node_modules/postgres/src/connection.js:440:44)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

Found a similar issue #854

### PR DESCRIPTION
**Pull request by cherrybarry**
Fixes #924

### CODE REVIEW

**Comment by porsager** [comment]
Thanks - looking good!

**Comment by karlhorky** [comment]
@porsager could we get a new release [`postgres@3.4.5`](https://github.com/porsager/postgres/releases/tag/v3.4.5) with this change?

I think we're running into server crashes similar to https://github.com/porsager/postgres/issues/924

**Comment by porsager** [comment]
Here you go @karlhorky https://github.com/porsager/postgres/releases/tag/v3.4.5 ;)

**Comment by karlhorky** [comment]
Amazing, thanks!! ❤️

**Pull request merged**
