### PR TITLE
expose table oid and att num from description

### PR DESCRIPTION
**Pull request by Newbie012**
While getting the description of a query, I need to get the table and the column attribute number (when there are any) as well.

According to the [docs](https://www.postgresql.org/docs/current/protocol-message-formats.html), it is possible to fetch these metadata from `RowDescription (B)`:

>Int32
If the field can be identified as a column of a specific table, the object ID of the table; otherwise zero.
>
>Int16
If the field can be identified as a column of a specific table, the attribute number of the column; otherwise zero.

My main goal is to eventually check whether a column is nullable or not.

### CODE REVIEW

**Comment by porsager** [comment]
Looks great ! Perhaps simply call the properties `table` and `number` ?

**Comment by Newbie012** [comment]
Sure! I have updated my changes

**Comment by porsager** [comment]
Awesome. Would you mind adding some tests that verifies the correct table oid and column number is received?

**Comment by Newbie012** [comment]
sure, but I'm having issues running the current tests:

```
➜  postgres git:(feat-expose-metadata) node tests/index.js 
⛔️ Connects with no options at line 39 failed 
PostgresError: password authentication failed for user "eliya"
    at ErrorResponse (file:///home/eliya/temp/postgres/src/connection.js:765:26)
    at handle (file:///home/eliya/temp/postgres/src/connection.js:468:6)
    at Socket.data (file:///home/eliya/temp/postgres/src/connection.js:312:9)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at cachedError (file:///home/eliya/temp/postgres/src/query.js:166:23)
    at new Query (file:///home/eliya/temp/postgres/src/query.js:36:24)
    at sql (file:///home/eliya/temp/postgres/src/index.js:105:11)
    at file:///home/eliya/temp/postgres/tests/index.js:42:28
```

```
PostgresError: password authentication failed for user "postgres_js_test"
    at ErrorResponse (file:///home/eliya/temp/postgres/src/connection.js:765:26)
    at handle (file:///home/eliya/temp/postgres/src/connection.js:468:6)
    at Socket.data (file:///home/eliya/temp/postgres/src/connection.js:312:9)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at cachedError (file:///home/eliya/temp/postgres/src/query.js:166:23)
    at new Query (file:///home/eliya/temp/postgres/src/query.js:36:24)
    at sql (file:///home/eliya/temp/postgres/src/index.js:105:11)
    at file:///home/eliya/temp/postgres/tests/index.js:59:33
```

what am I missing?

**Comment by porsager** [comment]
It is probably your pg_hba file that is not set up correctly. You can skip all tests på writing them using `ot` (only test) instead of `t`. Like this:

```js
ot('Include table oid and column number in column details', async() => {
  ...
  return [is, true]
})
```

If your test passes just commit with `t` instead of `ot` and github actions should run all tests ;)

**Comment by Newbie012** [comment]
Thanks for the tip. I believe it should be ok now.

**Pull request merged**
