### PR TITLE
add "bun" export condition and set "types" exports first as ts 4.7 requirement

### LINKED ISSUE #692: error: ResolveMessage after upgrade to v 3.4.0
**Runtime** : `bun 1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b`

Updating Postgres.js from 3.3.5 to 3.4.0, but then I got an error: ResolveMessage when executing a query.

```bash
ResolveMessage {
  stack: "undefined\n    at cachedError (/home/fahru/github-collections/postgres/node_modules/postgres/cf/src/query.js:171:27)\n    at new Query (/home/fahru/github-collections/postgres/node_modules/postgres/cf/src/query.js:35:47)\n    at sql (/home/fahru/github-collections/postgres/node_modules/postgres/cf/src/index.js:115:37)\n    at module code (/home/fahru/github-collections/postgres/index.ts:15:2)",
  query: undefined,
  parameters: undefined,
  args: [],
  types: null,
  code: undefined,
  importKind: undefined,
  level: undefined,
  message: undefined,
  position: undefined,
  referrer: undefined,
  specifier: undefined,
  toJSON: [Function: toJSON],
  toString: [Function: toString],
  name: "ResolveMessage",
  [Symbol(Symbol.toPrimitive)]: [Function: toPrimitive]
}
```

Code to reproduce
```typescript
import postgres from 'postgres';

const sql = postgres({
  host: 'random-generated-host.ap-southeast-1.aws.neon.tech',
  port: 5432,
  username: 'user_name',
  password: 'strong_password',
  database: 'database_name',
  ssl: true,
  max: 1,
  transform: postgres.camel,
});

await sql`SELECT id, "name", batch, migration_time FROM knex_migrations`.then((res) => {
  console.info(res)
  return res
}).catch((error) => {
  console.error(error)
})
```

It works on v 3.3.5
image

### PR DESCRIPTION
**Pull request by lukeed**
Closes #692 

Bun auto-matches a few conditions, including "worker" and "node". It looks for itself ("bun") first.
> See: https://bun.sh/docs/runtime/modules#importing-packages

Also made `types` the first condition, which is required according to the [TS 4.7 announcement blog](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/)

### CODE REVIEW

**Comment by porsager** [comment]
Sorry, I got to push a commit just before your PR :P Can you rebase to just have the types fix, then I'll merge.

**Comment by lukeed** [comment]
Haha i saw, slow UI :S 

Should already be updated

**Comment by porsager** [comment]
Seems like it.. My merge button hasn't even updated yet either - still thinks there are merge conflicts..

**Comment by Angelelz** [comment]
Thank you for working on this so quickly!

**Pull request merged**
