### PR TITLE
Add example for idle_timeout docs

### PR DESCRIPTION
**Pull request by karlhorky**
Ref #119

### CODE REVIEW

**Comment by porsager** [comment]
Cool.. Should be `idle_timeout` though ;)

**Comment by karlhorky** [comment]
Oh, oops, bad copy+paste! Fixed.

**Comment by mishanti** [comment]
Please update the readme to include that `idle_timeout` was renamed to `timeout`, thanks!

**Comment by porsager** [comment]
It's the other way around. Note that github master is v2 which is available on npm as `npm i postgres@beta` currently. You can find the v1 docs here http://npmjs.com/postgres or here https://github.com/porsager/postgres/tree/v1 (which has `timeout` correctly for v1).

**Pull request merged**
