### PR TITLE
Adjustment for better wording.

### PR DESCRIPTION
**Pull request by DavidPesta**

### CODE REVIEW

**Comment by porsager** [comment]
Replacing it with intervention removes the intended meaning. 
I think simply ending the sentence after `seamlessly` is better then.

**Comment by e3dio** [comment]
I think when it says "without user interference" or "without user intervention" it is meaning to say "automatically" which is a more accurate term to use, probably skipped it because it immediately follows "seamlessly" which would make it 2 "ly" adverbs in a row, somewhat awkward but still doable "come up and down seamlessly automatically"

**Comment by DavidPesta** [comment]
I updated it to use both words "seamlessly" and "automatically" without both appearing next to one another.

**Comment by e3dio** [comment]
Ah he already used "automatically" in the same sentence already taken nevermind

**Comment by e3dio** [comment]
Ok your edit is good I think

**Comment by e3dio** [comment]
Yeah too many automatically's in the same paragraph, not good. Probably intervention is more correct than interference

**Comment by DavidPesta** [comment]
no problem, changing it back to what i had originally then

**Comment by porsager** [comment]
> This allows multiple connections to seamlessly come up and down independently without affecting the service.

This is more what I had in mind.

**Comment by DavidPesta** [comment]
Oh, I thought point being made was that it happens automatically without the user/developer needing to do anything to handle doing it.

**Comment by e3dio** [comment]
It's already stated in section above that connections happen automatically so I think it's implied, but "without affecting the service" makes sense probably what was originally meant

**Comment by DavidPesta** [comment]
Ok, I like the clarity that the new wording adds. The words "user interference" was bothering me. This is probably good now.

**Comment by porsager** [comment]
👍

**Pull request merged**
