### PR TITLE
feat: don't override array type if already exists

### LINKED ISSUE #577: When a custom array parser is specified it still uses it's own
Specifying a custom array parser in options.types is just completely ignored.

For example using:
```ts
{
  to: 719, //719 = _circle (circle[])
  from: [719],
  serialize: () => {
    //...
   },
  parse: () => { 
    //... 
  },
}
```

### PR DESCRIPTION
**Pull request by Bas950**
Resolves #577

### CODE REVIEW

**Comment by Bas950** [comment]
> Looks great - Thanks a lot!

Yea no problem, found a few more errors, looking into those at the moment.
* #576 
* If you pass a custom OID parser it also gets used for internal functions which breaks a few things...

**Comment by Bas950** [comment]
@porsager Any release planned by any chance?

**Comment by porsager** [comment]
nope, but I'll make one today 👍

**Comment by Bas950** [comment]
Thank you!

**Pull request merged**
